### PR TITLE
Revert "punc, case, addition and some spelling mods"

### PR DESCRIPTION
**Pull request by asylumcs**
Reverts gutenbergbooks/30#13

### CODE REVIEW

**Comment by asylumcs** [comment]
This PR as submitted only corrects the text file, 30-0.txt. Changes were not provided in the PR for the corresponding HTML file, 30-h.htm.

**Comment by smichr** [comment]
A PR updating the html has been added. You can close this PR without reverting the changes that have been made to the flat text file. Both text and html will be synchronized once the html PR is committed.

**Comment by smichr** [comment]
Hmm...let me check that. I am not seeing all the html changes.

**Comment by asylumcs** [comment]
intentionally closing this PR without a merge.

**Pull request closed without merging**
