### PR TITLE
update html

### PR DESCRIPTION
**Pull request by smichr**

### CODE REVIEW

**Comment by asylumcs** [comment]
It's not clear to me now what needs to be done. Can you confirm that you want me to merge this pull request as it stands? You had asked for time to make sure you were "seeing all the HTML changes". If this is now ready to merge, let me know. You also sent some smaller PR's recently that were text-only. Does this PR reflect updating those commits as well? I would like to get this repository settled down, with matching content in the text and HTML versions. Then I can public it to the catalog.

**Comment by smichr** [comment]
The html changes are included in this now. The html changes bring the html up to date with the current version of the text, including all changes that have been made so far.

From my experience, the 1st commit of this PR will be ignored since it is already in place in the master branch. Committing this PR will only add the html changes. Then you can close the reversion PR without committing it.

**Comment by smichr** [comment]
I will close this and open a new one that has only the html changes so there is no question about what is going to be committed.

**Comment by smichr** [comment]
One note: since the html just unwraps the text of the verses anyway, I am not sure that it matters how the text is wrapped in the html itself. But in this PR, verses that were changed now appear wrapped to 71 characters while those that were unchanged are still wrapped at what appears to be 79 characters. I could make it so all verses remain wrapped at 79 characters. Either way, it will have no impact on how the html appears in a browser (only how it would appear in a text editor). Let me know what you would like.

**Comment by asylumcs** [comment]
Where the HTML lines wrap is immaterial since it makes no difference to how it is rendered to the user.

**Pull request merged**
